---
title: "2026 Budget Visioning Reflection"
description: "2026 Budget Visioning Reflection"
categories: Reflection
date: 1/25/2026
date-modified: 1/25/2026
author: Sam Jacobson
---

On January 20, in the Franklin Public Library, the new City Council met for its first workshop -- visioning the city budget for the upcoming year. This meeting was meant to provide direction and guidance for the City Manager to use when pulling together the budget for next year. It's worth noting that we are extremely early in the budget process.  

The discussion was reasonably focused. Below are my thoughts. These are subject to change as the council is presented new information and/or clarification: 

# Major Topics 

## Schools
This year is a negotiation year for the teacher contract, and the federal government has removed a series of grants from the schools. I am waiting to hear from the joint finance committee for more budget information, but I expect this to be a big discussion before the council.

Tax-capped budgets are hamstringing the SAU's ability to manage their district and provide state-mandated services. 


## Capital improvements 
Capital improvements (for example, road paving, fire truck replacement) are a major focus for the council. A number of councilors stated that they would be willing to put anywhere from $500,000 to $2.5 million toward the CIP. Councilor Carrier brought up that the 20 year replacement cost for roads was approximately $2 million annually. To replace the city's roads, the council needs to put $2 million every year toward them. This creates a 20 year schedule for replacement. Roads only get more expensive as they deteriorate. 

I am hesitant to bond for capital needs as they begin depreciating as the bond is being paid off. Additionally, I believe we have deferred maintenance for long enough. Folks in Franklin are looking for their government to function, and one basic way to do this is show stewardship of city owned property. 

I believe that the tax cap as written allows us to raise funds for capital needs, and I believe we should do so.

## Fire/EMS

The staffing levels in the fire department are at a point where we are losing professional firefighters and stacking more calls. I think the fire department could use another firefighter to provide better service and reduce overtime. 

The council discussed the option of encouraging private residents to volunteer for the fire/police departments in exchange for a tax break. This may save on personnel costs, but there are potentially significant training and equipping costs. I am skeptical that the fire chief could adequately incorporate volunteers into the schedule, and I need to be convinced that the professional firefighters feel comfortable relying on volunteers. 

# Trash, recycling, salting
Waste and snow management was discussed by several councilors and the Mayor. There seem to be some small optimizations/cost savings that can be found in the salt and sand management without really changing service. I think we should do these things, or understand why they are not being done. 

Trash pickup was discussed, more specifically if it would be cheaper to bring in house. I believe this has come before the council a couple of times, and the consensus is that it is cheaper to contract out to Casella. 

I would like to explore recycling as a potential costs savings (reducing the amount of waste that needs to be transported out of the city).

There are a lot of big ticket items in the city that need funding, and trash pickup as something that is not critical. I am open to moving it into a enterprise fund (e.g. water, sewer). 

# Other 
In general, I am concerned that the city will  have some unknown-unknowns coming in next year's budget. This year, we are getting hit with things like the Eversource-legal liability (up to $300,000) and shifting state level support for education (unknown dollar amount). These costs were not anticipated during the last budget process. Costs like these come out of nowhere will be challenges to budget for. 

We did not robustly discuss economic development, a key feature of Franklin's long-term sustainability. I look forward to the development of a master plan for the city of Franklin to guide longer term looks, zoning changes, and strategic positioning going forward. 