---
title: "Mar 4, 2026 Police"
description: "Second meeting of the Police committee"
categories: [Committee, Police]
date: 2/28/2026
date-modified: 2/28/2026
author: Sam Jacobson
---

# Location: Franklin Public Library

# Date: March 4, 2026

# Time: 5:30 PM

# Agenda
Below is what we intend to discuss.

1. Review minutes from the February 4 meeting.
2. Follow up discussion on pay scales
3. Other business

### How Sam Sees It: 
I expect the big point of discussion this meeting will be pay scales. At the last meeting, the Chief presented a plan to change the pay scales of the entire department in an effort to retain officers. Members of the Committee and City Manager wanted to see additional backup that the department could afford to change pay scales mid year while staying within budget. To make this change, the Chief of Police wanted to close open positions, an approach that may work in the short term but can lead to burnout via under-staffing. As shown in the fire department, under-staffing can lead to excessive overtime, which may cost more than hiring additional officers.  Additionally, solely changing pay scales in the police department may trigger resentment between other departments. 

I'm hopeful we'll have some additional budget backup provided to discuss, so that the Police committee can make a strong recommendation to the broader council. Right now, I understand the need to raise pay to retain officers, but am not convinced we can afford to. 