---
title: "July 23, 2026 Legislative"
description: "Legislative Committee meeting covering charter changes, winter parking and trash ordinance"
categories: [Committee, Legislative]
date: 07/20/2026
date-modified: 07/20/2026
author: Sam Jacobson
---


# Location: Franklin Public Library

# Date: July 23, 2026

# Time: 6:00 PM

# Agenda
Below is what we plan to discuss: 

1. Approve minutes from May 21 meeting
    - [Minutes](https://www.franklinnh.gov/legislative-committee) are located at the bottom right of the linked page. 
2. Charter Commission review
3. Proposed changes to charter
4. Winter Parking ordinance
4. Curbside trash ordinance review


## Agenda Breakdown

### 1. Minute Approval
Brenda Demers drafted minutes from the July 21 meeting, which I expect to approve with minimal changes. 

#### How Sam Sees it: 
Brenda has histroically done a fantastic job with the minutes. I don't expect major changes

### 2. Short Term Rentals (STRs)
At the May 21 meeting we dsicussed charter changes and a charter commission. The City Manager committed to brinign informaiton about what this process looks like to discuss with the legislative committee. 

#### How Sam Sees It: 
I expect the charter commission to be a belt an suspenders approach. We should explore both as this council does not have the appetite to change the charter on the 2026 ballot. 


### 3. Proposed Charter Changes
Over the last few months, this committee considered charter changes. I brought these forward at the June 1 City counicl meeting. Councilor Warner and others we not happy with the speed and combination of C-32 (tax cap) changes proposed. 


#### How Sam Sees It: 
At last two changes (Board of education to school board, neutralizing gender bias) will be brought before the public for a hearing on August 10. These changes will be on the ballot in 2027. 

I anticipate a further discussion on whether and how to discuss the tax cap (C-32) revisions and anticipate these moving later in the year. 


### 4. Winter Parking Ordinance
Director Chunn prepared a parking study; this committee will review and recommend ordinance changes. 

#### How Sam Sees It: 
The time to start on parkign is before the winter. I expect this to be multiple meetings, and involve significant discussion with the broader council. 

### 5. Curbside trash ordinance review
As part of the FY27 budget, the city manager proposed changes to the city trash collection. These may require ordinance changes. 

#### How Sam Sees It: 
This needs a significant amount of discussion. 