---
title: "May 20, 2026 Parks and Recreation"
description: "Third meeting of the Parks and Recreation Committee"
categories: [Committee, Parks & Rec]
date: 5/17/26
date-modified: 5/17/26
author: Sam Jacobson
---

# Location: Bessie Rowell Community Center

# Date: May 20, 2026

# Time: 5:30 PM

# Agenda
Update 5/18/26 with published agenda items

1. Approve minutes from 3/17/26 meeting
- I expect minor changes if any to the published [draft minutes](https://www.franklinnh.gov/parks-recreation-committee/minutes/parks-rec-committee-meeting-draft)

2. Director update
- I do not know wha tthe director will provide as part of his update. I hope a portion of it is budgetary in nature. 
3. Fee schedule for FY2027 discussion
- I do not know what this covers. 

4. Procedure, Policy, and Ordinance (parks) discussion
- I do not know what specific policies and/or procedures we will be discussing at this time. 

5. Upcoming park based events

6. Late Items


-----

Below is what I'd like to discuss: 

1. Approve minutes from 3/17/26 meeting
    - I haven't seen draft minutes yet, but I expect changes to be minor. 
2. Changes to City of Franklin summer programs
    -  One resident came forward at the May City Council meeting, mentioning potential changes to how out-of-community participants might be charged for utilizing Franklin summer programs. I'd like to know more from Director Carmichael on this issue. 
3. Fiscal Year 2027 budget and Expense update
    - Since we are getting into budget season, I'd like Director Carmichael to walk us through his budget, areas he had to cut, and changes he is proposing as he assumes leadership of the department.
    - At the previous Parks and Recreation committee meeting, Director Carmichael mentioned that he had 2027 expense projections complete. I'd like to review and discuss them with him and the rest of the committee.  
5. Other Business
