---
title: "September 17, 2026 Legislative"
description: "Legislative Committee meeting covering charter changes, winter parking and trash ordinance"
categories: [Committee, Legislative]
date: 09/06/2026
date-modified: 09/06/2026
author: Sam Jacobson
---


# Location: Franklin Public Library

# Date: September 17, 2026

# Time: 6:00 PM

# Agenda
Below is what we plan to discuss: 

1. Approve minutes from Aug 20 meeting
    - [Minutes](https://www.franklinnh.gov/AgendaCenter/ViewFile/Minutes/_08202026-174) are located in the agenda & minutes section of the . 
2. Winter parking ordinance
3. Curbside trash ordinance review
4. Short Term Rental 
5. Public Hearing review
6. Charter C-34 Discussion 
7. Other business 

## Agenda Breakdown

### 1. Minute Approval
Brenda Demers drafted minutes from the May August 20 meeting, which I expect to approve with minimal changes.

#### How Sam Sees it: 
Brenda has historically done a fantastic job with the minutes. I don't expect major changes.

### 2. Winter Parking Ordinance
Seek report from MSD on feasibility of downtown parking area. Also seek to understand alternative street plowing and how MSD could work with that. 

#### How Sam Sees It: 
Left off the last meeting wanting to know more about parking options in case of snow storm. The empty city owned lot at the corner of Elkins and Winnipasaukee are on the table as a short term lot, but need to know from MSD if they can get it prepared/manage it. 

Also need to consider if/how to permit parking and use city owned lots as an ongoing source of revenue. 

### 3. Curbside Trash Pickup Ordinance
Continue review of Manager proposed changes to trash ordinance. 

Summary of changes in ordinance: 

- Addition of fee language to the ordinances
- Institution of a sticker based system
- City still provides trash bins

Summary of requested changes: 
- Set flat fee for crossing scale
- Evaluate bag prices
- present an opt out procedure

#### How Sam Sees It: 
The draft ordinance provided is a good first step, but needs some additional information. I have a feeling some of these details (e.g. bag prices, flat fees on the scale) should be taken up by Municipal services committee.

### 4. Short Term Rentals (STR)
Seek to review STR issues in light of 2026 enforcement. This decision/schedule was put in place in the May 21 meeting. 

The last time this came before legislative there were two options:
1. An adaptation of Meredith's proposal that would require a effectively a permit and regular septic and code inspections. This also limited the number of days for owners "not in residence". 

- [Proposed Meredith style ordinance](../files/20260906_Franklin%20-%20STR%20Ordinance%20DRAFT%203.pdf)
- [Proposed Meredith style regulation](../files/20260906_Franklin%20-%20STR%20Regulation%20DRAFT%203.pdf)

2. A "lighter touch" that was a self attestation by the homeowner for safety inspections and septic inspections.

- [Proposed light touch regulation](../files/20260906_Trachy_Franklin%20STR%20ordinance%20draft%2051726.pdf)

Meredith revised its STR policy in 2026 following the first year of implementation reducing fees a bit and changing requirements about owners-in-residence. 

#### How Sam Sees It: 
I hope to come to the council with a final recommendation on STR (light touch, vs. Meredith style) after this meeting. Regardless of how this summer turned out, it seems that enforcement of STRs is dependent on the the city manager. This suggests to me that the current regulation is insufficient - it does not sustain itself between different City managers. 

This year we saw a shut down of Gryphon beach due to cyanobacteria. While likely a function of heat and farm runoff, septic systems are contributors to this issue too. 

The cost of these regulations to the homeowner are recouped by a handful of rental days. 

### 5. Public Hearing Review

During the August 31rd City Council meeting, the public hearing chapters were sent back to legislative for review. 
we were requested to reconsider the following: 

- Clarify what "posting" is. 

#### How Sam Sees It: 
I disagree with the need to have newspaper posting for public hearings, but what I heard from the council is that they want it. I suspect we will retain the newspaper posting piece and send the other parts of the suggested changes (e.g. allowing Planning and zoning to post notice) will be applied. 

### 6. Charter C-34 Discussion

Councilor Warner wants to review this section of the charter dealing with default budgets. 

#### How Sam Sees it: 
This year the City Manager presented a budget that was not balanced. The council was ~2 weeks from defaulting into this unbalanced budget, which would have been bad. I cna understand wanting to clarify this language and am eager to see what Councilor Warner will present. 

### 7. Other Business
None at this time. 