---
title: "September 22, 2026 Police"
description: "Fourth meeting of the Police committee"
categories: [Committee, Police]
date: 09/06/2026 
date-modified: 09/06/2026
author: Sam Jacobson
---

# Location: Franklin Police Department

# Date: September 22, 2026

# Time: 5:30 PM

# Agenda
Below is what we intend to discuss.

1. Review minutes from the June 11 meeting. 
2. Operational update from Police Chief
    - Staffing
3. Traffic Enforcement
4. Short term rental (STR) policy review, safety and enforcement. 
5. Other Business

[Previous meeting minutes](https://www.franklinnh.gov/AgendaCenter/ViewFile/Minutes/_06112026-153) can be found in the agenda & minutes section of the city website. 

### How Sam Sees It: 
I expect this meeting to be relatively routine with discussion focused on the operational updates from the police chief. I'm hopeful that the department was able to find qualified candidates for the open positions in the department. I don't know much about the traffic enforcement item.

The short term rental enforcement is meant to get police input as they may enforce STR infractions understanding their capacity to support is important. Since this meeting will follow the Legislative committee meeting discussing STR regulations, the police should have a final draft policy to weigh in on. 