---
title: "March 19, 2026 Legislative"
description: "Legislative Committee meeting covering short term rentals"
categories: [Committee, Legislative]
date: 3/15/2026
date-modified: 3/16/2026
author: Sam Jacobson
---

# Location: Franklin Public Library

# Date: March 19, 2026

# Time: 6:00 PM

# Rough Agenda
Below is what we plan to discuss: 

1. Approve minutes from Feb 26 meeting
    - [Minutes](https://www.franklinnh.gov/legislative-committee) are located at the bottom right of the linked page. 
2. Short term rentals (STRs)
3. Other business


## Agenda Breakdown

### 1. Minute Approval
Brenda Demers drafted minutes from the February 26, 2026 meeting, which I expect to be approved with minimal changes. 

### 2. Short Term Rentals (STRs)
Director Chunn will present an updated STR ordinance draft for review at the March 19 meeting. These are posted below. 

- [Draft STR Ordinance](/City%20Council/files/20260316_draft_STR_ordinance.pdf)
- [Draft STR Regulation](/City%20Council/files/20260316_draft_STR_regulation.pdf)

Currently, the city does not regulate STRs. STRs are typically single family homes used for a portion of time in a way that was not really contemplated or zoned, for example AirBnBs or Vacation Rentals By Owner (VRBO). 

At the last meeting, the committee discussed creating a permit process for STRs. Key questions from the last meeting included: 

1. What should the fee for STR permits be, and how long should they last? 
2. Should STR permits come through the Zoning Board of Adjustment? 
3. In which zones/portions of the city should STRs be allowed? 

#### How Sam Sees It: 
At the last meeting, Director Chunn presented a couple of good examples of STR regulation from Meredith and Laconia. Right now, I think we need some kind of licensing mechanism, and Meredith's approach seems to make sense. Key points of this are: 

1. Annual permitting with a fee attached. This fee offsets the inspection and response work conducted by the city for STRs.
2. STR permit applications go through the Zoning Board, which means abutters are notified, and fire, safety, and septic inspections are executed as part of the application process. Going through the Zoning Board also means the group of people reviewing permit applications have resident representation and experience reviewing permits. 
3. STRs allowed throughout the city (as they currently are). I don't think it's fair to require some sections of the city to get permits while others do not. 

I still believe STRs are a way for some homeowners to make more money from their property; however, their use can stress city infrastructure, change the character of neighborhoods, and warp property assessments. 

Fundamentally, the use of STRs changes the value of a property; it is no longer just a home, it now generates rental income. Our assessor does not seem to account for that in their home assessments, so I think the city should capture a portion of that additional income. 

Creating a permit for STRs allows the city of Franklin to understand the scope of STR use. Visibility to city enables an informed discussion on whether the city should promote or demote their usage. The city of Franklin needs some kind of regulation of STRs for clarity, in ways that will not expose the city to litigation. 

### 3. Other Business
As part of the last meeting, Councilor Warner requested to share his opinion and research on the tax cap portion of the charter at this meeting. We will not be discussing it in depth. 