---
title: "August 20, 2026 Legislative"
description: "Legislative Committee meeting covering charter changes, winter parking and trash ordinance"
categories: [Committee, Legislative]
date: 08/17/2026
date-modified: 08/17/2026
author: Sam Jacobson
---


# Location: Franklin Public Library

# Date: August 20, 2026

# Time: 6:00 PM

# Agenda
Below is what we plan to discuss: 

1. Approve minutes from May 21 meeting and July 23
    - [Minutes](https://www.franklinnh.gov/legislative-committee) are located at the bottom right of the linked page. 
2. Charter amendment procedure
3. Changes to public hearing procedure
4. Ordinance procedure revisions
5. Winter parking ordinance
6. Curbside trash ordinance review
7. Electronic device review
8. Other business 

## Agenda Breakdown

### 1. Minute Approval
Brenda Demers drafted minutes from the May 21 and July 23 meeting, which I expect to approve with minimal changes. The committee was not prepared to review the May 21 minutes at our last meeting. 

#### How Sam Sees it: 
Brenda has historically done a fantastic job with the minutes. I don't expect major changes.

### 2. Charter Amendment Procedure
Councilor Warner wants to develop a procedure for proposing Charter amendments. This is the beginning of that process. 

#### How Sam Sees It: 
I think the current process works fine - proposed changes come through legislative, then are brought to the full council. I don't see a need for more formal procedure, but am open to additional discussion. 

### 3. Changes to Public Hearing procedure
At the meeting on July 23, the City Manager brought forward this change to section 31 of the City code. This is intended to provide more flexibility for setting public hearings, 7 days rather than 10 days before a hearing, and remove the need to publish in the newspaper. 

#### How Sam Sees It: 
I think these changes are reasonable, 1 week of notice is pretty similar to 10 days of notice. Additionally, I think that the newspaper requirement is outdated as we do not have a newspaper that covers Franklin regularly or comprehensively. I could see replacing it with some kind of electronic (i.e. posting on the city website) instead. 

### 4. Changes to Ordinance procedure
At the meeting on July 23, the City Manager brought forward this change to section 68 of the City code. There are a series of changes to this piece of the code, affecting how ordinances are amended: 

- All changes have to go before the full council
- Public reading of the ordinance may be waived if there is a unanimous vote of the council
- If needed an ordinance can be sent to legislative for additional reworking
    - The legislative committee presents its work at the next practicable council meeting
- Removes the need for public hearings on standard ordinances
    - Pushes towards a public forum rather than a public hearing. 

#### How Sam Sees It: 
I like the flexibility this provides to legislative to respond when practicable as it gives more flexibility for a good faith effort of aligning schedules. I don't like removing the public hearing requirement. The push to public forum vs public hearing is a semantic one that doesn't really sit well with me. I understand that a public forum has fewer restrictions/noticing requirements, but the noticing is important. I don't think every ordinance change needs to be listed in the newspaper, but I think the general public should be made aware of changes to the code and provided an opportunity to weigh in. 



### 5. Winter Parking Ordinances
Director Chunn prepared a parking study; this committee will review and recommend ordinance changes. This study was not ready at the last meeting. 

#### How Sam Sees It: 
The time to start on parking is before the winter. I expect this to be multiple meetings, and involve significant discussion with the broader council. 


The main issue I see is that the city says no one can park on streets overnight during a snow storm, but does not provide a place to park (section 248 of the city code). Looking at section 248, there are 3 sections (B, C, D) that all say the same thing - you are not allowed to park overnight on a street or parking lot unless signed. Violators would be towed. I think this could be consolidated into one section, and then make clear that the city will identify parking areas during snow storms that are valid. We need to know where there may be parking spots to direct people to before sending them there. 

Additionally, folks need to be out of the parking lot soon after the snow storm so the lot could be cleared. This means violators would be towed. I think the city could identify one lot for this winter (i.e. off Winnipasaukee street) and see how it works (how many people use it etc. ) 

### 6. Curbside trash pickup ordinance
As part of the FY27 budget, the city manager proposed changes to the city trash collection. These require ordinance changes. These changes include: 

- Addition of fee language to the ordinances
- Institution of a sticker based system
- City still provides trash bins


#### How Sam Sees It: 
These changes make sense and align with discussions the City Manager has had with the Council. This is the first step to implementing the fee system for pickup. 

### 7. Electronic device policy review

During the August 3rd City Council meeting, the electronic device use policy was sent back to legislative for review. 
we were requested to add the following: 

- Exceptions for phone use for communications from family members

#### How Sam Sees It: 
This is a  reasonable exception to me. I'd also like to know which neighboring communities the City Manager spoke to when defining this policy. 


### 8. Other Business
None at this time. 