---
title: "2026-2027 Committee Assignments"
description: "Committee assignments for all Counselors"
categories: Committee
date: 1/19/2025
---
With each election, the committee assignments of councilors can change. Many (though not all) committees that are appointed by the Mayor have their root in the city charter. Most line up with a professional department head (e.g. Fire committee works closely with the fire chief). Committee meetings are the best way for public to engage/observe the discussion of department specific issues. Each committee makes regular reports to the broader council on their business and recommends department specific actions. Below is a list of the committees, description and current members. If you have questions about something that comes before that committee, contact those councilors!

These committees are where there is often frank, focused discussion on issues facing a given department. Many have not met in more than 6 months, a practice I hope changes under Mayor Morrill. 

# Finance
The Finance Committee deals with the finances of the city. Think is the city on budget for the year, any foreseeable budget/financial related issues that should be reviewed before being brought to the broader council. THe last meeting occurred in January 2026 (with the new members)!

- Delaney Carrier
- Al Warner
- Ben Forge

# City School Liaison
The City School Liaison Committee is joint between the city and school board and is meant to enhance communication between both bodies. It has not met in years. The last meeting I can find information from is November 2021. 

- Susan Hallett-Cook
- Ed Prive
- Tom Boyce

# Police
The Police Committee works with the chief of police to review department budget and policies. Think things like canine units and body camera usage. The last meeting I can find information from is May 2025. 

- Ben Forge
- Ed Prive
- Sam Jacobson

# Joint Finance
The Joint Finance Committee is made up of 3 City and 3 School Board members. It is intended to enhance communication between the school board and city regarding school finances. The last meeting I can find information from is October 2025.

- Al Warner
- Delaney Carrier
- Justine Hoppe

# Legislative
The Legislative Committee deals with city ordinances and policies. Think things like the winter parking ban, event permitting etc. The last meeting I can find information from is September 2025.

- Sam Jacobson
- Tim Johnston
- Al Warner

# Municipal Services
The Municipal Services Committee works with the director of municipal services to review department budgets and policy. THink things like road paving schedule, painting needs and capital needs for the department. The last meeting I can find information from is September 2025.

- Tim Johnston
- Delaney Carrier
- Tom Boyce

# Fire
The Fire Committee works with the fire Chief to review department budgets and policy. Think things like ambulance rates, inspection protocols, and capital needs. The last meeting I can find information from is May 2025.

- Tom Boyce
- Al Warner
- Justine Hoppe

# Parks and Recreation
The Parks and Recreation Committee works with the director of parks and recreation to review department budgets and policies. think things like events on city property and Bessie Rowell usage. The last meeting I can find information from is August 2024.

- Justine Hoppe
- Sam Jacobson
- Susan Hallett-Cook

# Capital Improvements Plan
The Capital Improvements Plan (CIP) Committee reviews and recommends changes to the city-wide capital improvements plan. The CIP is a list of all of the repair projects in the city.The last meeting I can find information from is December 2024.

- Ed Prive
- Ben Forge
- Susan Hallett-Cook

# Planning 
The mayor appoints one member of the planning board. This councilor joins teh other members of the community that are on the planning board to review applications before the planning board. The Planning board deals with subdivisions and site plans, land use regulations, and creating master plans for the city.  The last meeting I can find information from is December 2025.

- Delaney Carrier
- Tim Johnston (Alternate). Tim may step in when Delaney cannot attend a meeting. 

# Franklin Business & Industrial Development Corporation
The Franklin Business & Industrial Development Corporation (FBIDC)promotes the expansion of the economic base of the Greater Franklin area through targeted strategies to make the community an increasingly attractive location to conduct business, work and live. The mayor makes one appointment to this organization. FBIDC is similar to a Chamber of Commerce. The last meeting was in January 2026.

- Sam Jacobson




