---
title: "April 9, 2026 Legislative"
description: "Legislative Committee meeting covering short term rental regulation"
categories: [Committee, Legislative]
date: 4/5/2026
date-modified: 4/5/2026
author: Sam Jacobson
---


# Location: Franklin Public Library

# Date: April 6, 2026

# Time: 6:00 PM

# Rough Agenda
Below is what we plan to discuss: 

1. Approve minutes from March 19 meeting
    - [Minutes](https://www.franklinnh.gov/legislative-committee) are located at the bottom right of the linked page. 
2. Short term rentals (STRs)
3. Other business


## Agenda Breakdown

### 1. Minute Approval
Brenda Demers drafted minutes from the March 19, 2026 meeting, which I expect to be approved with minimal changes. 

### 2. Short Term Rentals (STRs)
Director Chunn will present an updated STR ordinance draft based on the discussion at the March 19 meeting. These will be posted as soon as possible. 


Drafts presented at the March 19 Meeting (note these have not been updated)

- [Draft STR Ordinance](/City%20Council/files/20260316_draft_STR_ordinance.pdf)

- [Draft STR Regulation](/City%20Council/files/20260316_draft_STR_regulation.pdf)

Currently, the city does not regulate STRs. STRs are typically single family homes used for a portion of time in a way that was not really contemplated or zoned, for example AirBnBs or Vacation Rentals By Owner (VRBO). 

At the March 19 meeting, the committee continued discussing a permit process for STRs. Key changes from the last meeting include: 

1. Septic inspections may be completed by a certified inspector in addition to NH department of environmental services (NHDES). 
2. Should there be an insurance requirement as part of the certificate? 
3. Fine collection (leins)? 
4. Expand certificates to include condos
5. Allow property managers to qualify as owner-in-residence (OIR) 
6. Increase the number fo days for OIR
7. Stiffen penalties for unaddressed violations
8. Changing parking to require at least one parking spot


#### How Sam Sees It: 
During the March 19 meeting, Director Chunn presented a strong first draft. We discussed a series of changes, and  I expect to have a draft complete ready to bring to the entire council in May. 

### 3. Other Business
As part of February 26 Legislative meeting, Councilor Warner requested to share his opinion and research on the tax cap portion of the charter at this meeting. We will not be discussing it in depth. 