---
title: "July 1, 2026 Parks and Recreation"
description: "Fourth meeting of the Parks and Recreation Committee"
categories: [Committee, Parks & Rec]
date: 06/28/2026
date-modified: 06/28/2026
author: Sam Jacobson
---

# Location: Bessie Rowell Community Center

# Date: July 1, 2026

# Time: 5:30 PM

# Agenda

1. Approve minutes from 5/20/26 meeting
- I expect minor changes if any to the published [draft minutes](https://www.franklinnh.gov/sites/g/files/vyhlif601/f/minutes/2026-05-20_parks_and_rec_draft-minutes_with_handouts.pdf)

2. Ordinance Update discussion and CAR planning
- At the last meeting Director Carmichael presented a [series](../../City%20Council/files/Draft%20P%26R%20Ordinance%20Updates.docx) of proposed ordinance changes.
- I'd like to bring these forward to the council. They include items like: 
    - Matching policy with current department names.
    - Empower Parks and Rec director to approve public dancing/performance instead of police chief.
    - Move fees (performance, park asset use etc) into published fee schedule.
    - Granting greater flexibility over park assets (beyond Bessie Rowell) for use. 
- I think these should be grouped into like minded items for discussion at the council (e.g. fees split separately from department names)


3. Public policy for parks and rec
- This is a public discussion to draft new policy for parks and rec. 
- Here is a [link](https://www.franklinnh.gov/home/news/help-shape-franklins-new-parks-policy%E2%80%94your-voice-needed) to more information