---
title: "June 11, 2026 Police"
description: "Third meeting of the Police committee"
categories: [Committee, Police]
date: 06/08/2026 
date-modified: 06/08/2026
author: Sam Jacobson
---

# Location: Franklin Public Library

# Date: June 11, 2026

# Time: 5:30 PM

# Agenda
Below is what we intend to discuss.

1. Review minutes from the March 4 meeting. Review minutes from the February 4 Police Committee meeting. 
2. Operational update from Police Chief
    - Staffing
    - New Hires
    - Regional Special Operations
    - Future Grant Opportunities
3. Late items

[Previous meeting minutes](https://www.franklinnh.gov/police-department/police-committee) can be found on the police committee section of the city website. 

### How Sam Sees It: 
I expect this meeting to be relatively routine with discussion focused on the operational updates from the police chief. At the last meeting we discussed changing pay scales to retain and attract new officers and I'm eager to see if that is bearing fruit. I am also appreciative of the enhanced public communications the police department (PD) appears to be doing. 

I'd like to hear a bit more of a preview of the PD budget for next year, and if there are any surprises the police committee should be aware of. 