---
title: "August 19, 2026 Parks and Recreation"
description: "Fourth meeting of the Parks and Recreation Committee"
categories: [Committee, Parks & Rec]
date: 08/17/2026
date-modified: 08/19/2026
author: Sam Jacobson
---

# Location: Bessie Rowell Community Center

# Date: August 19, 2026

# Time: 6:00 PM

# Agenda

1. Draft CAR review
- I drafted Council Agenda Reports (CARs) for the parks and rec committee to bring forward per Director Carmichael's identification.  These cover: 
    1. Expanding the ordinance language beyond Bessie Rowell to cover all parks and recreation assets.
    2. Moving the fee schedule from the Charter to the budget for clarity and consistency. 

I expect to review these and hopefully bring forward at the next City Council meeting.

2. Draft use policy
    - I am unsure what this is, but it may come from the discussion during the 7/1 meeting. 

3. Upcoming park based events


---

I also anticipate approving minutes from 7/1/26 meeting

- I expect minor changes if any to the published [draft minutes](https://www.franklinnh.gov/sites/g/files/vyhlif601/f/minutes/2026_07_01_parks_and_rec_draft_minutes.pdf)

