project: 
  type: website

website:
  title: "Franklin Forward"
  sidebar:
    style: "docked"
    search: true
    contents: auto

format:
  html:
    theme: slate
    css: styles.css
    toc: true

execute:
  freeze: auto