---
title: "March 3, 2026 City Council"
description: "Preview of topics for 3/2/2026 City Council meeting"
categories: City Council Meeting
date: 2/28/2026
date-modified: 2/28/2026
---

# Location: Franklin Elks

# Time: 6:00 PM

[Agenda](https://www.franklinnh.gov/sites/g/files/vyhlif601/f/agendas/2026-03-02_city_council_meeting_agenda.pdf)

[Packet](https://www.franklinnh.gov/sites/g/files/vyhlif601/f/uploads/council_packet_-_full_02_march_2026_0_0.pdf)

------------------------------------------------------------------------
This is a standard City Council meeting, starting with public hearings, public comment, and then moving onto council business. 

Below are my preliminary thoughts and initial positions going into the meeting. Please email me at <sjacobson@franklinnh.gov> if you would like to discuss further. 


## Agenda Items

## 1. Approval of Minutes 
-   Summary:
    -   Minutes from the February 2026 meeting.

### How Sam Sees It: 
- A couple of minor grammatical/attribution errors to address. 

## 2. Increasing Police Detail Rates
- Summary:
    - Police details are when a company or organization hires Franklin Police officers to provide services. This is typically traffic control (like when a cruiser sits near an electrical line repair truck).
    - Old rate: $95.00/hour; new rate: $110.50/hour.
    - Brings rates in line with other police details (e.g. Belknap County sheriff, Concord, Hill, Merrimack County).

### How Sam Sees It:
- We should charge similar rates to other departments. This brings in outside money to support city services. 
- Franklin Police Department should regularly reassess outside detail rates. I'd like to see annually as part of the budget process.  


## 3. Waiving Vendor Fees for Farmer's Market, Winni River Days, Community Day
-   Summary: 
    - Waive city-based fees for three community events.
    - Fees have been waived for these three events in the past. 

### How Sam Sees It:
- I think these events serve the community, and that these events should not have the additional burden of fees. 
- Small events like this are a great way for small businesses to hang their shingle/test product-market fit. We (the city) should encourage this.

### Questions: 
- How much is an individual vendor fee? How money is the city foregoing here?

## 4. Accepting Lead Abatement Money from the State
-   Summary: 
    - Schedule a public hearing for lead pipe abatement at Bessie Rowell.
    - New Hampshire department of Environmental Services (NHDES) will cover up to 100% of the cost of abatement.  
    - Currently, a portion of Bessie Rowell's water service is posted as not-safe to drink.

### How Sam Sees It:
- I think we should accept this money and conduct the remediation. 

## 5. Webster Lake NHDES Monitoring Station Access Agreement 
- Summary:
    - New Hampshire Department of Environmental Services (NHDES) seeks to install a shed near the boat ramp of Webster Lake. 
    - Shed will allow NHDES to automatically monitor lake level.
    - Agreement makes DES responsible for installation, upkeep and removal.  
    - Agreement lasts for 5 years with automatic renewal and 30 day notice for termination of agreement. 


### How Sam Sees It:
- This is a reasonable agreement and reasonable request from NHDES. We should approve this. 


## 6. Franklin Opera House Community Development Finance Authority (CDFA) Grant Memo
- Summary:
    - The Franklin Opera House (FOH) has an existing memorandum of understanding (MOU) with the City of Franklin that is actively being renegotiated. 
    - FOH applied for NH Community Development Finance Authority (CDFA) grants that require an MOU.
    - To help FOH's application for grant money from the state, the City Manager is asking the Council to affirm the existing MOU for 1 year. 


### How Sam Sees It:
- We should approve this on a provisional (i.e. 1 year) basis. It helps FOH get the supplies they need. It represents a grant funding opportunity, and the City has an existing MOU with FOH already. 


## 7. Setting a Workshop for School Budget Explainer
- Summary
    - Schedule a meeting for the School District to explain their budget process to the City Council.

### How Sam Sees It:
- In general, this seems like a good idea. The entire Council should understand how budgets work. 
- I'm a little concerned that this has not come through the Joint Finance Committee yet. This kind of process explainer should come through that committee. Additionally, this should be paired with an explainer for the municipal budget process, terminology, and structure. 

## 8. Naming New Street Piper Street
- Summary
    - Add name to newly constructed street before it normally would be added to help with emergency and postal services.

### How Sam Sees It: 
- Makes sense to me. 

## Other Business:
- Follow up on ambulance self-pay policy/discount.