---
title: "June 1, 2026 City Council"
description: "Preview of topics for 6/1/2026 City Council meeting"
categories: City Council Meeting
date: 5/31/2026
date-modified: 05/31/2026
author: Sam Jacobson
---

# Location: Franklin Elks

# Time: 6:00 PM

[Agenda](https://www.franklinnh.gov/sites/g/files/vyhlif601/f/agendas/2026-06-01_agenda_0.pdf)

[Packet](https://www.franklinnh.gov/sites/g/files/vyhlif601/f/uploads/2026-06-01_packet_0.pdf)

------------------------------------------------------------------------
This is a standard City Council meeting, starting with public hearings, public comment, and then moving onto council business.

Below are my preliminary thoughts and initial positions going into the meeting. Please email me at <sjacobson@franklinnh.gov> if you would like to discuss further. 

## Agenda Items

## 1. Approval of Minutes 
-   Summary:
    -   Minutes from the May 4,2026 City council meeting, May 8, 2026 Special City Council meeting, and October 20, 2025 City Council meeting. 

### How Sam Sees It: 
- No significant changes recommended. I was not on the council in 2025 nor was I present for the May 8th meeting so I will abstain from their approval. 

## 2. Request to Barricade Terrace Road 
- Summary:
     - There is construction ongoing near the Franklin-Northfield line that suggests a road may be created near Terrace road. 
     - Residents submitted a petition asking the end of Terrace Road be blocked off. 

### How Sam Sees It: 
- The plan provided shows a trail connecting the end of Terrace road to the Winnipasaukee River Trail (WRT). If true, there would not be an increase to car traffic through Terrace street. 
- Placing boulders at this time seems preemptive. I'd like to direct the City Manager to be the point of contact here to monitor the situation. 
- If a road is planned, I'd like to see the developer come to the City council to discuss the tie in (or lack thereof).
- Generally I don't want to spend time moving rocks unless there is a certain problem. 



## 3. Sell Sterling Drive Turnaround Parcel
-   Summary: 
    - Residents of Sterling drive community submitted a petition seeking to add land that from the roadway to a parcel. 
    - There is ambiguity in some of the plans defining a "temporary turnaround" during construction. 
    - The city owns the roadway. 
    - Abutters of this turnaround suggest that they own the parcel having cared for it for 20 years and not the city. 
    

### How Sam Sees It:
- I'd like to send this to the City's legal council with a deadline to review the strength of the City's claim to the temporary turnaround. 
- I understand the desire to reclaim land from the City when the City is not taking care of it. 
- This may be an attempt to stop the logging going on through Sterling drive by asserting private ownership of an access way, but I am not certain. 

## 4. Set Schedule for 2026 (FY27) Budget Workshops
- Summary:
   - Set the schedule for budget workshops. 
   - Budget workshops are City Council workshop meetings that focus on aspects of the city budget, prior to final approval. 
   - These are workshop meetings. This means limited public input, but more discussion between the members of the council. 


### How Sam Sees It:
- I think we should have 4 budget workshops: 
    - School
    - Police/MSD
    - Fire/Parks and Rec/Library
    - City Manager's office and other 

## 5. Revised Event Permitting and Permits for Alcohol Use
- Summary:
    - Events using alcohol on city property need a permit.
    - This ordinance has been revised through legislative, through the council, and legal.
    - The proposed regulation does the following
        - Uses a better definition of alcohol
        - Regulates **consumption** and sale
        - Add the mayor or designee to the permit approval process


### How Sam Sees It:
- I still do not believe that the mayor should be approving event permits. 
- I am eager to see the other changes approved as this has been kicking around for months. 


## 6. Bessie Rowell Lead Abatement
- Summary
    - Accept money from the State of New Hampshire for lead abatement at Bessie-Rowell Community center. 
    - This was mistakenly left off the April Agenda. 

### How Sam Sees It:
- This was an oversight by the council. 
- We should accept this money and use it to reduce lead exposure for children. 


## 7. Fire Engine Replacement
- Summary
    - The fire department (FD) is budgeting for a new engine to replace one of two active engines in the city. 
    - The full price is ~$1.1M and the FD proposes to buy it in sections; ~$550,000 in Fiscal year (FY) 2028 and ~$550,000 in Fiscal year (FY) 2029.
    - The engine set to be replaced is difficult to service and was out of operation for maintenance reasons for more than 50 days this year.  

### How Sam Sees It: 
- I appreciate the FD budgeting this across two years and I'd like to hear if they have any revenue streams to cover it. 
- This is the prime application of a capital improvement exemption from the tax cap. I'd vote to exempt the cost from the tax cap calculation in 2028. 


## 8. Set Public Hearing to Revise Wetlands Ordinance
- Summary
    - Set a hearing to change wetlands septic setback requirements. 
    - City of Franklin (75 ft setback) is more protective than the state (50 ft setback) regarding septic systems near wetlands. 
    - The proposed revision allows septic systems 25 feet closer to wetlands than now. 

### How Sam Sees It: 
- I think we should set this hearing. 
- I think we can change our statute to match the state, providing we highlight that in other cases (e.g. surface water bodies) the largest setback (75 ft) still applies
    - For instance, installing a septic system near webster lake still needs a 75 ft setback, even if this change is accepted. 


## 9. Set Public Hearing to Stiffen Code Violation Penalties
- Summary
    - Currently the city can charge up to $100/day for code violations. 
    - The state allows up to $550/day for code violations.
    - The suggested change would link city penalties to the relevant state code and make fines for code violations larger. 

### How Sam Sees It: 
- I think this makes sense, especially in the extreme cases of years of non-compliance (evidenced by 528 Prospect street).
- This passed the planning board with one detractor and lengthy debate. I'd like to know why. 
- There is still discretion in the ordinance based on the severity of the fine. 
- We should schedule this public hearing. 


## 10. Sell City-Owned Land on East Bow Street
- Summary
    - The owner of 102 East Bow Street has made an offer of $3,000 for 0.13 acres of vacant city land abutting their property. 
    - This property generated ~$600 in taxes last year that could be returned to the rolls; however merging properties is not necessarily additive. More or less than that might be captured from the new value of the property. 



### How Sam Sees It: 
- Other abutters should be given the chance to bid on this property. 
- $3,000 seems low 



## 11. Set Hearing for Charter Change on School Board
- Summary
    - Schedule hearing for charter change, needs at least 7 days in the newspaper. 
    - Put on a question on the ballot in October to make language referring to the school board consistent in the Charter


### How Sam Sees It: 
- I think we should schedule this hearing




## 12. Set Hearing for Charter Change on Gender Bias
- Summary
    - Schedule hearing for charter change, needs at least 7 days in the newspaper. 
    - Put on a question on the ballot in October to reduce the gender bias in the Charter




### How Sam Sees It: 
- I think we should schedule this hearing. 

## 13. Set Hearing for Charter Change on Tax Cap
- Summary
    - Schedule hearing for charter change, needs at least 7 days in the newspaper. 
    - This proposal includes a couple of potential changes: 
        - clarify how exceptions to the tax cap are calculated in successive years (e.g. bond payments)
        - Increase the scope of what expenses can be exempted from the tax cap calculations. 
        - Allow additional increases to the tax cap every 5 years. 

### How Sam Sees It: 
- I think we should schedule this hearing. 
