---
title: "June 29, 2026 City Council"
description: "Preview of topics for special 6/28/2026 City Council meeting"
categories: City Council Meeting
date: 06/28/2026
date-modified: 06/28/2026
author: Sam Jacobson
---

# Location: Franklin Public Library

# Time: 6:00 PM

[Agenda](https://www.franklinnh.gov/sites/g/files/vyhlif601/f/agendas/2026-06-29_cc_agenda.pdf)

[Packet](https://www.franklinnh.gov/sites/g/files/vyhlif601/f/uploads/2026-06-29_packet.pdf)

------------------------------------------------------------------------
This is a City Council meeting, starting with public hearings, public comment, and then moving onto council business.

Below are my preliminary thoughts and initial positions going into the meeting. Please email me at <sjacobson@franklinnh.gov> if you would like to discuss further. 

## Public hearings

1. 2024 CDBG grant funded project for 36 affordable housing units at 11 plains court.
2. 2023 CDBG grant funded project for the Healthfirst family care center.
3. Commentary on the FY27 school board budget.  

## Agenda Items

## 1. Consider resolution 19-26: Administrative Clean up of Industrial TIf money
- Summary:
    - In 2025, the City Council voted to close the industrial park tax increment financing (TIF) district.
    - The council voted to put to ~$360k of money from the TIF into "roads".
    - This agenda item seeks to move that money out of the general fund and into a dedicated account. 

### How Sam Sees It: 
- This is a procedural change; in general I am for it. 
- This speaks to the importance of preparing for motions, especially when moving money between accounts. 

#### Questions: 
- The original motion (3-26) and the motion prepared reference different amounts($369k vs $396k). Why?

## 2. Paving East Bow Street
- Summary:
     - There is current paving ongoing on East bow street. 
     - The manager seeks $67k to repave all of East Bow, as the equipment and material have been mobilized already.
     - Money would from the Capital improvement account referenced in Agenda item 1. 

### How Sam Sees It: 
- This seems like an efficiency and a good use of money
- I live off Bow Street and would like to see them pave it instead of patchwork repairs. 

## 3. Paying accounts payable into fiscal year 2027
-   Summary: 
    - The city budget will not be competed and approved by July 1.
    - July 1 is the first day under the new fiscal year.
    - This motion allows the city to pay payroll and certain bills for the month of July.
    - Amounts are taken from the proposed FY27 budget.
    
### How Sam Sees It:
- We should approve this to avoid late fees and make payroll.