---
title: "August 03, 2026 City Council"
description: "Preview of topics for 8/3/2026 City Council meeting"
categories: City Council Meeting
date: 08/02/2026
date-modified: 08/02/2026
author: Sam Jacobson
---

# Location: Franklin Elks

# Time: 6:00 PM

[Agenda](https://www.franklinnh.gov/sites/g/files/vyhlif601/f/agendas/2026-08-03_agenda.pdf)

[Packet](https://www.franklinnh.gov/sites/g/files/vyhlif601/f/uploads/2026-08-03_packet_0.pdf)

------------------------------------------------------------------------
This is a standard City Council meeting, starting with public hearings, public comment, and then moving onto council business.

Below are my preliminary thoughts and initial positions going into the meeting. Please email me at <sjacobson@franklinnh.gov> if you would like to discuss further. 

Note that this preview includes late items that have been distributed.


## Agenda Items

## 1. Approval of Minutes 
-   Summary:
    -   Minutes from eight City Council workshops in June and July
        - Most of these are budget related. 
    - Minutes from July 6th City Council meeting  

### How Sam Sees It: 
- No significant changes recommended.

## 2. Memorandum of Understanding (MOU) for Franklin Outing Club (FOC)
- Summary:
    - In January, the City began requiring  a signed memorandum of understanding (MOU) with outside entities, particularly non-profit organizations. 
    - This is the first MOU to come before the council.
    - FOC has provided ski/snow recreation opportunities since 1963.
    - FOC operates and maintains all facilities and ski trails at the veterans memorial ski area.
    - FOC has to make an operating plan and approve it through the City.
    - MOU details 
        - 21 year agreement
            - Can be terminated by 2/3 of City Council, or FOC with 90 day notice
        - Agreement evaluated annually
        - Possibility (i.e. required bookkeeping) of annual audit
        - FOC owns all concessions, expenses, utilities, machinery, equipment. 
        - Changes to the lodge become the City's
        - City pays for liability insurance, club pays for worker's compensation insurance and liquor insurance.


### How Sam Sees It: 
- I think this MOU writes down a lot of what has previously been happening between FOC and the City.
- I am surprised to see the FOC taking on workers comp insurance as this was handled by the city in the past.
- I do not like how much control this gives the city council over an independent entity; however they have reached mutual agreement on terms.  
- I am happy to see the first MOU come before the council.
- This set's minimums on the City's contribution to the FOC, but additional support or in kind support could be offered in the future on an ad hoc basis. 

## 3. Pump House Replacement
-   Summary: 
    - FOC wants to demolish the pump house and replace with a larger pump.
    - This would allow better water transfer to snow making equipment.
    - FOC is working with NH Department of Environmental Services (DES) to authorize/evaluate water takings. 
    - No cost to the city.
    - Permits provided to City Council. 

### How Sam Sees It:
- This will save FOC volunteer time and enhance snow making.  
- This will not cost the city anything.
- I think the council should approve this. 

## 4. Lease Agreement for 117 Cheney Street
- Summary:
   - Johnathan Wolfgram wants to lease a City owned vacant lot at the bottom of Cheney Hill for a personal garage.
   - Another neighbor does not want it used this way. 
   -Lease details
        - Backdated to June 2026
        - 1 year lease
        - $155/month ($1,860/year)
        - 10% late fee if lease is not paid
        - Waive security deposit
        - Utilities, maintenance, snow, trash, paid by Mr. Wolfgram
        - Property improvements paid by Mr. wolfgram, to be approved by the city
        - Used as parking/storage
            - No hazardous waste storage
        - $1 million liability insurance held on the property and certificate provided to the City
        - City gets fire insurance, Mr. Wolfgram reimburses the city. 
        - Sale of property terminates lease


### How Sam Sees It:
- This seems like a fair lease and a reasonable way to return property to the tax rolls. 
- A neighbor has come forward in the past to share impacts to neighborhood aesthetics for parking a truck there. This is as important as returning the property to use in my mind. 
- Other constituents have discussed the danger of backing out/parking on Cheney hill; this is similar to any resident living on Cheney Hill. Mr. Wolfgram and/or the drivers of the vehicles are responsible for handling their vehicles safely. 
- At this time, I'd approve this lease. 

### Questions
    - Why is this lease backdated? 
    - On what month would the city start collecting rent? 

## 5. Electronic use policy for City Council and other meetings
- Summary:
    - The council has requested a draft electronic use policy (phones, computers etc.) 
    - All devices are subject to right to know (RSA 91-A) laws. 
    - Policy
        - Applies to all members and any device (personal or otherwise) used during a meeting
        - Approved uses
            - Reviewing meeting material
            - Taking notes
            - Looking up factual information
            - Communicating with city staff
            - Participating in the meeting remotely
        - Prohibited uses
            - Personal texting/social media use
            - Inappropriate, disrespectful or unbecoming communication
            - Communication with another member of the body in private (i.e. texting another councilor how they'd vote privately)
            - Unauthorized recording
        - Devices should be silenced
        - No enforcement/penalties

### How Sam Sees It:
- I think the council should be able to use electronic devices.
- I use a computer to take notes, organize meeting material, and communicate with constituents.
- I have observed other councilors apparently texting each other during meetings which this may address
- Without penalties, I am concerned this will not stop the texting at the table. 
- I would accept this policy as a start. 


## 6. Moving debt and interest payments outside of the tax cap
- Summary
    - At the July 29 public hearing the council postponed this motion
    - Moving $618,269 outside the tax cap and moving that money to the school budget
    - The motion was postponed for two reasons
        - Whether this was permissible under the city charter
            - We received a legal opinion from the city lawyer that this was permissible under the city charter
        - How much this would cost to a typical property owner
            - This would cost $0.53 per $1,000 of assessed value
            - For a $300,000 property it would be $159.00

### How Sam Sees It:
- I made this motion and think it should pass as the school is in need of funding from the city this year. 
    - To date, this council has provided approximately $53,000
    - The total school budget is approximately $19,100,000
- I am concerned as similar legally permissible methods have been voted down by this council with smaller dollar amounts. 
- I expect this to fail in favor of the third late item. 


## Late Item 1: Undoing previous council debt financing  of ambulance
- Summary
    - At the July 29 public hearing the council postponed this motion
    - In 2024 the council voted to order an ambulance and pay for it using debt
    - This council has voted to pay for it outside the tax cap.
    - This helps clarify the record/supersedes the older motion.  


### How Sam Sees It: 
- I am in favor of moving the ambulance outside the tax cap, this is one component of that. 

## Late Item 2: Purchase Ambulance outside of tax cap
- Summary
    - At the July 29 public hearing the council postponed this motion
    - Cost of the ambulance is $466,289
    - Saves $100,000 in interest over the life of the loan
    - Cost is $0.40 per $1,000 of assessed property value
        - For a $300,000 property it would be $120.00

### How Sam Sees It: 
- I'm generally in favor of moving the ambulance cost outside the tax cap.
- I'm also sensitive to the stacked moves outside the tax cap (159 from moving debt outside for the school, and 120 for the ambulance).
- This opens up budget for operational expense and is an appropriate use of Charter section C32-B. 
- I'd like to see the City budgeting and setting aside money for this and similar capital projects to lessen individual tax bills. 
- The $60,000 in savings is going to pay the Eversource litigation liability. This liability was paid in 2026 by this council taking money from the restricted fund balance. Taking money from the fund balance must be replaced, and this Council starts each year for the next 4 years, $60,000 behind.
    - Councilor Johnston worked to close the industrial park TIF, taking the ~$350,000 and moving it into the general roads account instead of using it to pay for the eversource liability. Money in the industrial park TIF was collected from the commercial properties in the industrial park. Effectively, the tax payers are paying for the Eversource litigation liability instead of commercial property owners. I think this is foolish. 


## Late Item 3: Authorizing the movement of debt outside the tax cap to pay for school

- Summary
   - This is a repeat/formalized motion of the agenda item above. 
    - Moving $618,269 outside the tax cap and moving that money to the school budget
    - We received a legal opinion from the city lawyer that this was permissible under the city charter
    - This would cost $0.53 per $1,000 of assessed value
        - For a $300,000 property it would be $159.00


### How Sam Sees It: 
- I'm not sure why this is repeated, but I think we should move this money one time.