---
title: "January 5, 2026"
description: "Preview of topics for 1/5/26 City Council meeting"
date: 1/4/26
---


# Location: Franklin Elks

# Time: 6:00 PM

[Agenda](https://www.franklinnh.gov/city-council-mayor/pages/city-council-meeting-information)

[Packet](https://www.franklinnh.gov/city-council-mayor/pages/city-council-meeting-information)

------------------------------------------------------------------------
This meeting is split into two parts, old business (covered by the exisiting council and Mayor), and new business (covered by the winners of the 2025 election). 

Below are my preliminary thoughts and initial positions going into the meeting. Please email me at <sjacobson@franklinnh.gov> if you would like to discuss further. Note that all **new** business is public hearings and/or workshops, so you will have time learn more and advocate before the council votes. 

**Agenda & Packet have not been posted on the city website as of 9:45 PM on Sunday, January 4th.**

## Old Business 
## Public Hearings

1.  Consuming alcohol on City-owned property
2.  Revitilization district signage
3.  Veteran's tax credit changes
4.  FSD fund balance

## Discussion Items
1.  Minutes
2.  Alcohol permits
    -   There are process-related issues outlined by the city manager in the packet that should be rectitfied. I believe this should go back to legislative committee to address before the council adopts. 
    -   I don't like the mayor being involved in the decision making process. We hire professionals to do this job (City Manager, Fire Chief, Police Chief) to both protect the city from liability and evaluate the risks. The Mayor does not have that experience.
3.  Revitilization district signage
    -   Allows for open signs and restricts total signage from 33% to 20% following discussion with Heritage Commission.
    -   No enforcement mechanism laid out.
4.  Veterans Credit
    -   I like this. Maintains tax benefit for veterans and disabled veterans following changes at the state level.
5. Franklin School District fund balance
    -   This is an item that has been in front of the council for a couple of months. Overages in the school budget were related to unexpected healthcare costs and less revenue provided by the state.
    - The school has fund balance in their budget to pay for this.  
    - Pass this already!
6. MOU
    -   This process feels like a burden on various non-profits throughout the city. In particular, the increased financial reporting and minutes required during revenue generation or construction activities. It's not clear to me the full scope of the non-profits in this city and what problem this is trying to solve. Additionally, there is a transparency issue as meeting minutes/audio recordings beyond October 30th do not appear to be publically avialable. The documents submitted in the January 5th packet appear to be from an external organization, without a link to who wrote them or where they come from.

## New Business

## 1. Committee Meeting Schedule
-   Summary:
    -   Councilor requests for agenda items are due Wednesday before scheduled meeting.
    -   Information supporting a late item needs to be brought forward with as much heads up as possible.
    -   If a late item doesn't have documents available beforehand, it is pushed to the next meeting.

### How Sam Sees It: 
- I like this, as it sets standards for how/when to use late items and promotes preparation. Hopefully this will reduce the need for and use of late items. 

## 2. Salary for Mayor and Council
-   Summary: 
    - Set a hearing for the council and mayor
    - Current compensation is set in the charter at $25/meeting for councilors and a max of $2,000/year for the mayor. 
    - Seeks to set the salaries at a single amount for all councilors in the name of efficency.
    - This is a routine meeting. Most councilors and mayors donate their salary back to the city. 

### How Sam Sees It:
- I think we should hold this public hearing.
- I think we should set the salaries for the mayor and councilors at the same time because it is more straightforward for the city administration.
- I think the mayor and councillors should donate their salaries back to the city. 

## 3. Ambulance Fee Pricing
-   Summary:
    -   Setting a hearing to change the ambulance fee schedule.
    -   Changes to state law to avoid balance billing, starting a cost study statewide.
    -   City Manager and Fire Chief began negotiating to allow more-than-Medicare rate. If the city does not start negotiations, we are locked into Medicare rate. 
    -   Now can bill up to 325% of Medicare rate, but cannot balance bill.
    -   Council will vote on final contracts with insurance providers.

### How Sam Sees It:
- This allows us to collect more money from private insurance while negotiations are ongoing.

#### Questions
- How much is this line in our budget?
- How much do you expect the EMS billing to increase?
- If you are on Medicare or Medicaid, what does this change?
- If you are uninsured, what does this change?
    - How many uninsured people are provided ambulance transport each year?

## 4. Surplus Fire Equipment
-   Summary: 
    - Surplus equipment sale to community/private businesses.

### How Sam Sees It:
- This brings in revenue and removes old/outdated equipment. We should do this.

## 5. Late Item: Budget Vision Workshop
-   Summary: 
    - Set council workshop for budget visioning for the city.

### How Sam Sees It:
- I think this is a good idea as it provides transparency and clear direction for the city manager and department heads.