---
title: "September 28, 2026 City Council"
description: "Preview of topics for 9/28/2026 City Council meeting"
categories: City Council Meeting
date: 09/28/2026
date-modified: 09/28/2026
author: Sam Jacobson
---

# Location: Franklin Elks

# Time: 6:00 PM

Agenda - No separate agenda provided. See page 2 of packet for agenda. 

[Packet](https://www.franklinnh.gov/AgendaCenter/ViewFile/Agenda/_09282026-198)

------------------------------------------------------------------------
This is a standard City Council meeting, starting with public hearings, public comment, and then moving onto council business.

Below are my preliminary thoughts and initial positions going into the meeting. Please email me at <sjacobson@franklinnh.gov> if you would like to discuss further. 

## Agenda Items

## 1. Approval of Minutes 
-   Summary:
    - Minutes from City Council meetings in August and September. 
        - August 31 is a regular City Council meeting.
        - September 14  is a workshop on Robert's rules of order.

### How Sam Sees It: 
- No significant changes recommended.

## 2. Surplus Fire Equipment Sale
- Summary: 
    - Accept ~$10,000 in revenue from equipment sales. 
    - List of equipment was provided in January. 

### How Sam Sees It: 
- We should accept these funds. 

## 3. Set Hearing for Grant Funding for Schools
- Summary: 
    - Set public hearing for accepting grants and reserve money totalling  $550,044. 
    - $200,000 from NH Dept of Education Safe and  Supportive Schools for social and emotional wellness of students. 
    - $255,000 from Crotched Mountain Foundation for the development of the lakes region special education consortium.
    - $44,200 from David M Brooks Music Education Program for music programs. 
    - $28,478 from the Special Education Capital Reserve fund for special education costs in FY27. 
    - $22,365 from School facilities Capital Reserve Fund for facilities costs in FY27. 

### How Sam Sees It:
- We should accept grant money for the schools. 

#### Questions
- Crotched mountain money is split over three years, shouldn't we  accept the money every year as it is awarded?
- How much money is in the special education and facilities capital reserve funds? 

## 4. School Fund Balance- hearing on Oct 13
- Summary:
    - School district spent $87,295 over budget in FY 26. 
    - School district took in $178,286 over revenue in FY 26. 
    - This uses the extra revenue to cover the extra expenses, leaving $90,991 in fund balance for FY27. 
    - This money is found via 'clean up' at the end of the year - invoices and contracts that do not match budget. 
    - Propose hearing for Oct 13.
 
### How Sam Sees It:
- We should set this hearing. 
- We should use the school revenue to pay for the school expenditures and accept this proposal. 

## 5. Set hearing for Paving North Main Street
- Summary:
    - Set hearing for October 13. 
    - $289,174 to pave ~3,800 ft of road from Benson's to Webster lake road. 
    - Money to come from Municipal transport improvement fund

### How Sam Sees It:
- I'm in general in favor of paving roads. We should set this hearing. 
- I'd like to see two more quotes for this work.  
- The quote references Cheney hill and victory, where are those quotes. Broadly, why this street? 
      - Other streets identified by CIP are Cheney Hill, Prospect, Pleasant, and N Main street. 
    - N Main is scheduled for water service conversion in the CIP from 10" to 12" conversions. I don't want to pave only to rip it up again. 


## 6. Hearing for Davis, Birch, Jason Street Paving
- Summary:
    - Set hearing for October 13. 
    - $54,922 to pave Davis, Birch, Jason streets. 
    - Money to come from Municipal Transportation Improvement Fund. 
 
### How Sam Sees It:
- I'm in general in favor of paving roads. We should set this hearing. 
- Why Birch and Jason streets? 
- I'd like to see at least 3 quotes for this work. 

#### Questions
- How much money is in the Municipal Transportation Improvement Fund?

## 7. Solid Waste Ordinance
- Summary: 
    - Change code to allow for sticker system for trash pickup
        - Stickers are:
            - $65 for a small (48 gallon barrel)
            - $90 for a medium (64 gallon barrel)
            - $125 for a small (96 gallon barrel)
        - $1.25/20 lbs of trash at the transfer station

### How Sam Sees It: 
- This aligns the code with the budget for this year. 
- We need to implement this system in order to balance the city budget this year. 
- I'd like to set a minimum fee to drive over the scale, especially for lower volumes of trash. (e.g. 5$ to drive over the scale), and per weight charges > 100 lbs of waste.  

#### Questions
- What is the cost of the orange bags for disposal at the transfer station? 


## 8. Private Companies in Parks and Recreation Center Assets
- Summary:
    - Section 309 of of City code includes says commercial groups can use assets (like Bessie Rowell) if sponsored by a local organization.
    - There is an exception for local private companies (i.e. local private companies can use Parks and Rec assets).
    - This proposal removes that exception.

### How Sam Sees It: 
- This should go to the parks and rec committee for further discussion. It's not clear what problem this is solving. 
- Prioritizing local businesses for park usage is fine by me - I'm not sure that this needs to be changed.
- Parks and rec assets are still subject to approval by the parks and Rec director. 

## 9. Potential Tax Cap Amendment to Legal Council - Clarifications

- Summary:
    - Schedule a public hearing on tax cap clarification. 
    - This is similar to the amendment proposed at the June 1 City Council meeting. 
    - Seeks to trigger the  charter amendment process.
        - Public hearing, then legal review, then state officials.
    - Amendment clarifies that costs outside of the tax cap (e.g. capital costs) are not included in the next year's calculations


### How Sam Sees It: 
- We should schedule this hearing and notice this hearing. 
- I'd like to see it scheduled on October 13 to coincide with other city business.
- I understand the desire to add this language, however I do not think it is necessary. The council can always approve a budget beneath the tax cap (i.e. manually remove the capital costs from the previous year). 
- I don't feel particularly strongly about this. 

## 10. Potential Tax Cap Amendment to Legal Council - Reassessments

- Summary:
    - Schedule a public hearing on tax cap change. 
    - This is similar to the amendment proposed at the June 1 City Council meeting. 
    - Seeks to trigger the  charter amendment process.
        - Public hearing, then legal review, then state officials.
    - Amendment adds maximum 3% additional increase every 5 years
        - This change accounts for differences in inflation and other unforeseen costs. 
        - If this were implemented in the FY 27 budget, property taxes could have increased $608,594 (3%) in addition to the $711,298 (3.5%). 


### How Sam Sees It: 
- We should schedule this hearing and notice this hearing. 
- I'd like to see it scheduled on October 13 to coincide with other city business.
- Because these increases are only possible to be made every 5 years, it tends to lead to years with big hits. I think shrinking the length of time and tightening the exception (e.g. max 1%, every 2 years ) would smooth tax changes. 
- As written this may require accounting for 3% over multiple years, which could be confusing (i.e. what is the base year for calculating the changes?).
- This could be sequenced to align with off-year elections to enhance their importance and focus for the community. 

## 11. Eversource Easement
- Summary: 
    - Grant Eversource permanent easements to access their infrastructure off of Flaghole road and Rt 127. 
    - Generate $5,000.
    - Contract notes
        - Eversource can make improvements to property, but improvements can be removed when contract ends. 
        - Eversource to purchase and install gate with shared locks for the city.
        - City becomes responsible for gate. 
        - Eversource is responsible for damages. 

### How Sam Sees it: 
- $5,000 seems low and arbitrary. 
- Eversource should retain responsibility for their gates. 
- Eversource should have to leave improvements to the property, similar to MOU with Franklin Outing Club. 
- I'd like to see a mechanism for ongoing assessment, or renegotiation of easement. 

#### Questions
- Is this a form agreement, or specific negotiation? 
- Where did the $5,000 come from? 
 
## 12. Selling Water to Tilton
- Summary: 
    - Developer on Terrace road wants to tie into Franklin water. 

### How Sam See's it: 
- I need more information from the developer before making a decision. 
    - I'd like to know who pays for installation and maintenance of infrastructure
    - How much water they are planning to use?
    - How much water the city of Franklin has?
    - Plans for Franklin's water use(i.e. are we constraining development of Franklin's tax base by going through with this?).
- I'm not opposed to selling water in concept, but need more information. 

## 13. Purchasing MSD Equipment
- Summary: 
    - Set a public hearing for October 13
    - Pay $22,700 for the following items
        - Trailer
        - Truck body
        - Pavement saw
        - Plate compactor plate
    - Money comes from the FY27 Budget ($5,500) and MSD capital reserve ($17,200)
 
### How Sam See's it: 
- I think we should have at least 3 quotes for the trailer and truck body given that they are more than $5,000. 
- I think these funding streams and costs make sense to replace. 
- We should schedule this hearing. 

## 14. Selling Old MSD equipment
- Summary: 
    - Old an broken MSD equipment to be auctioned off, proceeds return to MSD capital fund.
    - Complete list provided in packet. 


### How Sam See's it: 
- We should sell this equipment and return the money to the the MSD department. 

## 15. Memorandum of understanding (MOU) Deadline
- Summary: 
    - Set deadline of November 1, 2026 for all organizations to start MOU process with city. 
    - If an organization has not started the process, bar them for using city assets. 

### How Sam See's it: 
- This feels arbitrary and fast. 
- I'd like to know if there are organizations that are wilfully ignoring the MOU process, and why. 
- I'd like to see this pushed to December 31, 2026 with more targeted outreach. 
- The city council has only now begun to review and approve MOUs. 
- I'd like to know how many organizations are working on MOUs. 


# Other Business

### How Sam Sees it: 
- The City Manager is due for a 1 year review. The City Council should schedule this. 