---
title: "August 31, 2026 City Council"
description: "Preview of topics for 8/31/2026 City Council meeting"
categories: City Council Meeting
date: 08/29/2026
date-modified: 08/29/2026
author: Sam Jacobson
---

# Location: Franklin Elks

# Time: 6:00 PM

Agenda - No separate agenda provided as of 8/29/26. See page 2 of packet for agenda. 

[Packet](https://www.franklinnh.gov/AgendaCenter/ViewFile/Agenda/_08312026-181)

------------------------------------------------------------------------
This is a standard City Council meeting, starting with public hearings, public comment, and then moving onto council business.

Below are my preliminary thoughts and initial positions going into the meeting. Please email me at <sjacobson@franklinnh.gov> if you would like to discuss further. 

## Agenda Items

## 1. Approval of Minutes 
-   Summary:
    - Minutes from City Council Meetings in August. 
        - August 3 is a regular city council meeting.
        - August 11 is a non-meeting as there was not a quorum.
        - August 14 is the approval of the FY27 budget.

### How Sam Sees It: 
- No significant changes recommended.

## 2. Memorandum of Understanding (MOU) for Franklin Outing Club (FOC)
- Summary:
    - In August the FOC brought their MOU forward and the City Council sent it back with revisions.
    - The changes to the draft MOU are as follows: 
        - 50% premium cost sharing for city liability insurance.
        - Mutual notification if agreement is terminated.

### How Sam Sees It: 
- I think this MOU writes down a lot of what has previously been happening between FOC and the City.
- I think the City should pay for the premiums on the liability insurance policy. This places an unneeded burden on the FOC non-profit and is a departure from decades of precedent. 
- I am surprised to see the FOC taking on workers comp insurance as this was handled by the City in the past.
- I am happy to see the first MOU come before the Council.
- This set's minimums on the City's contribution to the FOC, but additional support or in kind support could be offered in the future on an ad hoc basis. 

## 3. Public Hearing for Revenue from Sale of Surplus Fire and EMS Equipment
- Summary: 
    - Seeks to set a hearing at the next City Council meeting to accept ~$10,000 in revenue from equipment sales. 

### How Sam Sees It:
- We should schedule and hold this hearing.

## 4. Emergency Plan Adoption
- Summary:
    - The Fire chief, Police chief, and others developed emergency plans between May and July 2026.
    - Emergency plans reflect updates recommended by state agencies. 
    - These plans help coordinate personnel and equipment in emergencies. 
    - Plan was available for review by the public on May 7 and should be available on the City website.
    - The last time this plan was updated was in 2020. 

### How Sam Sees It:
- I'm generally in favor of regularly updating emergency procedures.
- The supplied link in the agenda does not work, I have not had a chance to review the plan. 

## 5. FEMA floodplain Management
- Summary:
    - The Federal Emergency Management Administration (FEMA) has added another requirement to flood insurance. 
    - This is administrative and lack of action may cause loss of coverage.

### How Sam Sees It:
- I think we should approve this amendment so as not to lose insurance coverage, or reduce eligibility for residents. 
- It's not clear to me what the amendment is, as the suggested language in the suggested motion is dated in the future (November 2026).


## 6. Parks and Recreation Fee Schedule
- Summary:
    - Currently the fees associated for parks and recreation are listed and defined in the city code.
    - This seeks to move the fee schedule in the budget to connect it more closely to the budget process. 
    - Moving out of the code allows more flexibility for the Parks and Recreation director and council to change rates as needed. 

### How Sam Sees It:
- This motion came out of the parks and recreation committee.
- I think we should move these fees out of the code and into the budget. 

## 7. Electronic Use Policy
- Summary: 
    - The draft electronic device policy was kicked from the City Council to the Legislative committee on August 3rd. 
    - The Legislative committee reviewed this policy on August 20, and added a handful of additional exceptions.
    - This policy is meant to:
        - Focus the council during meetings.
        - Prevent side discussions out of public view.
        - Set an expectation for use of different meeting aids. 
    - These policies are not enforceable, but it is a commitment by the councilors. 

### How Sam Sees It: 
- I think we should adopt this as it enhances transparency and builds trust with the public. 

## 8. Expand Definition of Park Asset
- Summary
    - The Parks and Recreation department manages more than just Bessie Rowell Community Center (BRCC) but the code and policies governing the Parks and Recreation department are focused on BRCC.
    - This expands the definition of asset in the code to provide clearer legal foundation for things like permitting and use policies. 

### How Sam Sees It: 
- This came out of the Parks and Recreation committee
- It's mostly procedural and is a clarification that the director wanted for his policymaking. 
- These changes seems reasonable to me. 


## 9. Public Hearings Revision 

- Summary:
    - This is a change that came out of legislative committee making three changes to public hearings: 
        - Expands who can post public hearings to more than just the City Clerk.
            - This makes it easier for people like planning and zoning (who have their own legal requirements to notice hearings) to complete these obligations. 
        - Shortens the required post time to seven days prior to the hearing from ten days prior to the hearing.
        - Removes requirement to post in the newspaper.


### How Sam Sees It: 
- Note that removal of the newspaper does not mean public notice is not made; rather it recognizes that a newspaper may not be the best avenue for public hearing notices. 
- I'd like to see public hearings posted in cheaper more broadly accessible ways like email blasts, flashing signs on central street, website notifications. 
- These changes make sense to me and should be adopted. 

## 10. Changes to Ordinance Revision Procedure
- Summary: 
    - This seeks to simplify and clarify the process for changing the city code.
    - The changes do things like: 
        - Clarifies that public hearings are not mandatory for every ordinance change.
        - Removes the need to publish changes in the newspaper, and record in a physical book in City Hall.
        - Requires ordinance changes and new ordinances to come before the entire council.

### How Sam Sees It: 
- I think these changes makes sense
- It reduces the reporting needs, but maintains the public notice for changing ordinances. 
- It sets a more reasonable floor for ordinance changes; on a case by case basis the council could advertise ordinance changes more broadly. 

## 11. Winnipasaukee River Basin (WRB) Transition
- Summary: 
    - The WRB manages wastewater throughout the lakes region, including Franklin. 
    - The WRB is currently administered by NH department of Environmental services (NHDES) 
    - The managers of the WRB suggest member communities manage the program themselves to save costs, instead of running through NH DES. 
    - The WRB board has a couple of examples of poor management by NHDES wasting ratepayer dollars and notes that NH DES is focused on enforcement not operating. 

### How Sam Sees it: 
- I'm not ready to support this at this time. 

#### Questions
- How much do we pay into this system now, where is it trending for Franklin, and how much we can expect to pay under our own management.
- Do we lose protection for Franklin's cost and/or state support if we leave the NH DES management? 

## 12. Set a September Workshop
- Summary: 
    - Set a workshop on September 14 on Robert's rules.

### How Sam See's it: 
- I don't think this is necessary. 
- I'd prefer it held the following Monday (9/21). 

## 13. Proposed Charter Amendments - School Board
- Summary: 
    - Following public comment on the proposed amendment, the final amendment language has to be sent to the state for review. 
    - See [previous post](../Workshops/20260810_charter_amendment_rename.qmd) for more information. 

### How Sam See's it: 
- THis is a straightforward charter change with limited impact. It is a test on how to actually change the charter, while we have time to change it. 
    - Changing the charter is like working a muscle, you have to start slow. 

## 14. Proposed Charter Amendments - Neutralizing Gender Bias
- Summary: 
    - Following public comment on the proposed amendment, the final amendment language has to be sent to the state for review. 
    - See [previous post](../Workshops/20260810_charter_amendment_rename.qmd) for more information. 

### How Sam See's it: 
- This is a more consequential charter change that that impacts many different sections. It is a further test on how to actually change the charter.
    - Changing the charter is like working a muscle, you have to start slow. 

# Other Business
- Appointing Deborah Burley to the Ward 1 Election Moderator. 