---
title: "How Much Property does the city own?"
description: "Using the axis GIS to figure out where and how much property the city owns"
author: "S Jacobson "
date: "2025-12-27"
categories:
  - analysis
---
test text


```{r load libs}

library(tidyverse)
library(sf)
library(tmap)

ttm()
```

```{r read in data}

fp2<-  here::here("data/20251116_geo_dat/caidump.DBF")
dat<- foreign::read.dbf(fp2) %>%as_tibble()


parcel_polys_fp<- here::here("data/20251116_geo_dat/parcel_polys.shp")
parcel_polys<- st_read(dsn = parcel_polys_fp)
zone_fp<- here::here("data/20251116_geo_dat/zone_polys.shp")
zone_polys<- st_read(zone_fp)


zone_polys %>% filter(str_detect(NAME, "Frank")) %>% st_cast("MULTIPOLYGON") %>% 
tm_shape() + 
    tm_polygons(fill = "NAME")

#zone_polys %>% 
#  tm_shape() + 
#    tm_polygons(fill = "NAME")

parcel_polys%>% 
tm_shape() + 
    tm_polygons()

```

```{r map it}

d2<- dat %>%
   mutate(across(.cols = c(MAP, LOT),.fns =  ~str_sub(., -3)),
          SUB = str_sub(SUB, -2)) %>%
 
  mutate(PARCEL_ = paste(MAP, LOT, SUB, sep="-"))

comb<- parcel_polys %>%
  left_join(d2)  %>% drop_na(MAP) %>%
  mutate(across(ends_with("VAL"), as.numeric)) %>%
  mutate(year_sale = year(SALEDATE),
         years_since_sale = 2025-year_sale)

comb %>% filter(STATE != "NH")%>%
  tm_shape() +
  tm_fill("STATE")


```
