---
title: "July 15, 2026 - Budget Workshop 8: Council Line Movements Continued"
description: "This is a Council meeting to discuss the overall city budget and specific line movements. I anticipate water and sewer fee discussion"
categories: Workshop
date: 07/14/2026
date-modified: 07/14/2026
author: Sam Jacobson
---

# Location: Franklin Public Library

# Date: July 15, 2026

# Time: 6:00 PM

[Packet/Manager's Proposed Budget](https://www.franklinnh.gov/sites/g/files/vyhlif601/f/pages/fy2027_city_manager_budget_proposal.pdf)

[School Board Proposed Budget](../../Other%20Posts/FY2027_budget_review/FY27_budget_docs/combined_school_budget.pdf)

------------------------------------------------------------------------

This is the eighth meeting of the budget review process in the City. This will be a workshop meeting.

Below are my preliminary thoughts and initial positions going into the meeting. Please email me at <sjacobson@franklinnh.gov> if you would like to discuss further. Please note I will be attending via phone due to a prior work commitment. 

Check out the [Budget hub](../../Other%20Posts/FY2027_budget_review/FY2027_Budget_TOC.qmd) for department specific run-downs. 

------------------------------------------------------------------
## Agenda Items
## 1. Budget Discussion
Throughout the month of June, the City Council reviewed the City Manager's proposed budget line-by-line. This is a chance for the City Council to see where the City Manager wants to spend money. At the meeting on 7/13, the council voted on the largest piece of the budget, the school. Tonight I expect us to talk about the following: 

- Water rates
    - 2026 rate $7.68 / 100 cubic feet
    - 2027 proposed rate $8.22 / 100 cubic feet
- Sewer rate
    - 2026 rate $11.64 / 100 cubic feet
    - 2027 proposed rate $11.64 / 100 cubic feet

### How Sam Sees It

The water and sewer departments are enterprise funds, i.e. they fund themselves. I was surprised to see a larger rate increase this year, but believe it could be reasonable. I am eager to learn more about how this rate is derived. 