---
title: "April 13, 2026 - School Budget Explainer"
description: "How to read and interpret the school budget"
categories: Workshop
date: 4/11/2026
date-modified: 4/11/2026
author: Sam Jacobson
---

# Location: Franklin Public Library

# Date: April 13, 2026

# Time: 6:00 PM

[Agenda](https://www.franklinnh.gov/sites/g/files/vyhlif601/f/uploads/2026-04-13_city_council_workshop_agenda.pdf)

[Packet](https://www.franklinnh.gov/sites/g/files/vyhlif601/f/uploads/2026-04-13_council_packet_workshop_0.pdf)

This workshop is a presentation from SAU administrators how to read the school budget. This is intended to build on the understanding of the municipal budget from the last workshop meeting (March 23, 2026). 

There are two other agenda items: 

1. Setting a public hearing for eversource litigation payment
2. Late item: Leasing river street parcel to Brent Fife


This should be a straightforward explainer of how to read the school budget, put on by the administrators of the school administrative unit (SAU). I anticipate Jefferson, the SAU business administrator, will be presenting how to read a generic budget. 


## Other Agenda Items

## 1. Setting a hearing for the payment of eversource litigation
- At the city council meeting on April 6, 2026, the council rejected the City manager's proposal to use money recovered from the industrial park TIF (moved to the capital improvements plan [CIP] - roads budget). This agenda item sets a public hearing for the new plan - using restricted fund balance to fund the litigation payment.
- Use of restricted fund balance in this way requires __starting__ each year in a ~70,000 deficit. 

### How Sam See's it
- I think we should set this public hearing. 
- Starting each year in a deficit is poor financial planning. I have yet to hear how we might pay for this recurring expense. 
- The council has had months to come up with alternate ways to pay this expense, unsuccessfully. 

## 2. Leasing River Road Acreage to Brent Fife to Farm

- Historically this approximately 34 acres of city-owned land has been leased to Brent Fife to farm. 
- Lease term highlights: 
    - one year term of lease
    - $25/acre (~$850 total)
    - only agricultural use
    - 60-day cancellation provision
    - crop harvest protections included in lease
    - hazmat (pesticide) outside of label use not allowed
    - city indemnified for injury and/or death
- Same lease as in 2025

### How Sam See's it
- 25$/acre feels low to me. I think we should engage the assessor to see if this is an appropriate rate. 
- I understand there may be current use guidance for $25/acre price (RSA 79-A) but I understand that this may be outdated. 
- Though this is a small amount of money, every dollar counts for this city. 
- The last lease was signed in May 2025, and so I don't think there is time pressure to sign this one at this workshop meeting. 

