---
title: "January 20, 2026 - Budget Visioning"
description: "Budget visioning between City Council, Mayor, and City Manager"
categories: Workshop
date: 1/19/2026
date-modified: 1/19/2026
author: Sam Jacobson
---

# Location: Franklin Public Library

# Date: January 20, 2026

# Time: 6:00 PM

This is a chance for a workshop meeting between the City council, Mayor, and City manager to discuss budget priorities heading into Fiscal Year 2027. This is intended to be the start of the budget process, giving the professional staff (City manager, department heads) something to aim at. It also provides a time early in the budgeting process for the City manager to raise known issues and strategies.

City councilors will have last year's budget to start from. I expect this will be broadcast on zoom - the franklin city website is the best place to look for that. [link to city website](https://www.franklinnh.gov/city-council-mayor/pages/city-council-meeting-information). 

Hope to see you there.  



### How Sam Sees It: 
This will be the first budget constructed by City Manager Kloewer. 

During the fiscal year(FY) 2026 budget process, acting City manager Clarenbach spoke to the need for the council to consider and guide him on potential service reductions to address deferred maintenance and other longer-term budget issues. From my perspective, the sitting council did not really grapple with that request. 

At the same time, I've heard from many constituents that Franklin has a revenue problem, i.e. we need to figure out how to bring in more money. 
 
This process will not be easy, but I'm hoping the Council and City Manager will find common direction coming out of this meeting.

This is a high level vision/strategy session, no concrete FY2027 budget numbers will be addressed. 


