---
title: "August 10, 2026 - Public Hearing on Charter Changes"
description: "This is a public hearing on two proposed charter changes, one dealing with schools and one dealing with gender bias."
categories: Workshop
date: 08/06/2026
date-modified: 08/06/2026
author: Sam Jacobson
---

# Location: Franklin Public Library

# Date: August 10, 2026

# Time: 6:00 PM

[Agenda](https://www.franklinnh.gov/sites/g/files/vyhlif601/f/agendas/2026-08-10_agenda-tentative.pdf)

No packet has been provided for this hearing

------------------------------------------------------------------------

This is a public hearing on two proposed changes to the Franklin city charter. It is a requirement of the charter amendment process described in [RSA 49](https://law.justia.com/codes/new-hampshire/title-iii/chapter-49-b/section-49-b-5/). The basic process is as follows: 

1.  A charter amendment is proposed and passed by the City Council
    - The proposed amendments were crafted in the legislative committee in April and May and brought to the full Council on June 1. 
2. The proposed amendment is discussed in a public hearing.
    - The hearing scheduled for August 10th is that hearing.
    - If there are substantive changes, a new hearing is held. 
3. The proposed amendment is sent to the NH Secretary of State, Department of Revenue Administration and Attorney General for review. 
    - They may require changes, which sends this back to step 1. 
    - If approved, it goes to the city council for action. 
4. The Council votes to put it on the ballot (i.e. in an October election) for a vote from all registered voters. 

Below are my preliminary thoughts and initial positions going into the meeting. Please email me at <sjacobson@franklinnh.gov> if you would like to discuss further. I am currently traveling for work, and likely will not be able to participate in this meeting fully. 

If you would like to submit comment directly, you may do so via the [city website](https://franklin-service-requests-39a5.vercel.app/?page=public-input).

------------------------------------------------------------------
## Agenda Items

## 1. School Board Rename

[Text of amendment](https://www.franklinnh.gov/sites/g/files/vyhlif601/f/uploads/2026-08-10_notice_website.pdf)


Summary: 

- The charter is inconsistent in how it refers to the elected body that oversees the schools. This replaces "board of education" with "school board". 

#### How Sam Sees It: 
- This is a simple, non-consequential change to the charter. I see this as a way to test how to actually change the charter. Franklin has not changed its charter voluntarily for years, perhaps decades. 
- This may help residents navigate the charter (i.e. easier searching for a colloquial phrase than a legal one from the 1960's).

## 2. Neutralizing Gender Bias

[Text of amendment](https://www.franklinnh.gov/sites/g/files/vyhlif601/f/uploads/2026-08-10_notice_website.pdf)

Summary: 

- Removes gendered language throughout the charter 
    - For example the charter  assumes that the city manager is a man or that the mayor is a man in certain provisions. 

#### How Sam Sees It: 
- I see this as a more significant proposal. Women have led and will hopefully continue leading this community and our governing documents should recognize them. 
- While this does not substantively change city operation (we've had a woman serve as mayor under this biased charter), the bias in the charter is noticeable. 
- It provides further practice for making charter changes. 

## 3. Discussion of the public hearing

Summary: 
- Following the public hearing the council needs to refer the proposed amendments (assuming there are no changes) to the clerk for filing with the state.  

#### How Sam Sees It: 

- This is procedural, but important to react to public input. 