---
title: "Feb 26, 2026 Legislative"
description: "Legislative committee meeting covering Event permits, Short term rentals, and other items"
categories: [Committee, Legislative]
date: 2/15/2026
date-modified: 2/15/2026
---

# Location: Franklin Public Library

# Date: February 26, 2026

# Time: 6:00 PM

# Rough Agenda
We are still working to finalize the agenda. Below is what I'd like to discuss: 


1. Approve minutes from 1/27 meeting 
2. Event permit reform 
3. Short term rentals (STR)
4. Charter changes
5. Economic development & tax cap
6. Winter parking 
7. Other Business


## Agenda Breakdown

### Minute approval
- Councilor Warner drafted minutes from the Jan 27, 2026 meeting which I expect to be approved with minimal changes. 

### Event Permit Reform
- In the [old business of the January 2026 meeting](/City%20Council/files/202601_event_permit_car.pdf), changes to event permitting process were sent to the legislative committee for review. there are a series of changes to be considered: 
    1. Defining a special event permit in the code. This is the crux of the City Manager's request to send to legislative. The alcohol use section of the city code does not specify where a permit should be picked up, which might be confusing.The after-hours use of beaches/parks routes through the police department now. 
    2. The proposed alcohol permit appeal mechanism is not clear, sometimes it goes to the broader council, sometimes it is not defined.  
    3. The lawyer recommends the use of "alcohol" vs. "intoxicating liquor" for more clarity in the code.   

#### How Sam Sees It: 
- I think this mistakes the functions of the city council and the committee composed of the experts (City Manager, Fire chief, Police chief, Parks and Rec Head) in the city. Sections C and D insert the city council as both the approver and appellate body - which doesn't make sense to me. I think it makes more sense to keep the city council as the group that is appealed to after the committee of experts weighs in. 

- Similarly I don't believe the Mayor should be a part of the committee of experts. The point of this committee is to evaluate the safety, preparation, and planning of the organization's use of alcohol. The Mayor would have time to weigh in on the process during an appeal process - assuming the City Council stays as the appellate body. 

#### Short Term Rentals (STR)
Currently, the city does not have a Short Term Rentals (STR) ordinance. Short term rentals are things like AirBnB's or vacation rentals by owner (VRBO). A single family home is used for a portion of the time in a way that it was not really contemplated or zoned. STRs are a way for some homeowners to make more money from their property, however there use can stress city infrastructure, change the character of neighborhoods, and warp property assessments. 

#### How Sam Sees It: 
The city of Franklin needs some kind of regulation of STRs for clarity, in ways that will not expose the city to litigation. The director of planning and zoning will be presenting a draft STR policy for review as well as comparative studies of other communities like Meredith. A quick google search shows that communities face this differently:

- Meredith
    - Provides definitions as less than 30 days of occupancy for a rental
    - Separates owner-in-residence vs. not
    - Puts limits on number of people per bedroom (2)
    - Adds septic, fire, and parking checks
    - Contact info provided

- Wolfboro
    - Limits guests per bedroom (2) + 2
    - Provides for fire, septic and parking checks
    - Requiring NH Meals and rooms tax ID
    - Contact info provided

- Berlin
    - Not addressed (as far as I can tell)

Recent changes to the Accessory dwelling unit (ADU) in the city code that make them easier to construct, have to potential to make STRs more prolific in the community. I see this is something that needs to be regulated by the city. 

### Charter Changes
Councilor Warner sent a series of potential charter changes to bring to the broader Council from the [August 2024 Legislative meeting](/City%20Council/files/081924_legislative_committee_minutes_-_approved.pdf). These charter changes will have to be added to the ballot to be adopted and are summarized as follows: 

- C-2, Moving Wards into ordinance
- C-3, Changing councilmen to councilors
- C-7, Change election day to align with state/national elections
- C-13, Change board of education to school board
- C-16, Tie votes/disputed elections
- C-17, Revise duties of supervisor of the checklist
- C-32, Reset or adjusting the tax cap
- C-53, Conflict of interest


#### How Sam Sees It: 
Eight changes to the charter (though some are more straightforward than others) is likely too much for a single year. I'd like to work as a legislative committee to bring 3 recommendations for ballot additions to the broader council in time for elections this year. I think this should be two "find-and-replace" changes (e.g. Board of education to School Board) and one substantive (e.g. Revise or adjusting the tax cap). Note that the specific wording of the ballot change would have to some through legislative. 


### Economic development committee
During the [July 16, 2025 legislative committee meeting](/City%20Council/files/071625_legislative_committee_minutes_-_approved.pdf), there was a discussion of creating an economic development committee. A proposal was forwarded to the city's lawyer and no response (to my knowledge) has been received. 

I see no need to move on this until we receive a report back from legal. 

### Tax cap referral
During the budget workshop meeting on January 20, 2026, Councilor Warner wanted to understand the how the [charter](https://ecode360.com/10175836?highlight=tax&highlight=taxes&searchId=9744524952871378#10175836) defines raising money via taxes or bonds to pay for capital needs. He was concerned that one council's actions might encumber the following council and requested referral to the city's lawyer. 

I see no need to move on this until we receive a report back from legal.

### Winter parking 
Director Chunn agreed to present a parking study he had conducted to support winter parking ordinance changes. Since we are almost through winter (and any action form legislative is unlikely to take effect until after winter parking has been resolved), I think we should pick this up in the May 21 meeting.