---
title: "FY2027 Parks and Recreation Budget "
description: "Discussion of the FY2027 proposed Parks and Recreation Budget"
categories: Budget
date: 06/10/2026
date-modified: 06/21/2026
author: Sam Jacobson
---

This is part of my review of the FY2027 Budget and covers the parks and recreation department.

# FY2027 Proposed Expenses 
- Total recreation: $1,220,759
    - 3 full time staff, 1 part time
        - Director wages: $98,781
        - Full time/part time staff wages: $159,177
        - Seasonal staff wages: $300,019
    - Summer rec supported by the 21st century grant: $200,000
        - $45,000 for bus rental 
    - $757,000 of the parks and rec budget is wages
- Some expenses offset totally or partially by revenue

## Questions
- To what extent did former director Alpers prepare this budget? 
- How many seasonal staff are you budgeting for? 
- Why is there a 49% change in workers comp this year? 
- 01-5-211-40299-000 Recreation Admin Mileage Reimb ($500) does not match the description (water samples etc. )
- Since revenue is a key portion of the parks budget, how are revenues looking this year? Are we generally tracking above or below our projections? 