---
title: "FY2027 School Budget "
description: "Discussion of the FY2027 proposed School Budget"
categories: Budget
date: 06/10/2026
date-modified: 06/12/2026
author: Sam Jacobson
---

This is part of my review of the FY2027 Budget and covers the School. The school board presented their [budget](FY27_budget_docs/combined_school_budget.pdf) on 6/8/26. The school baord previously shared a [budget explainer](FY27_budget_docs/SAU18%20Budget%20Guide%20L%20Cass%2026-27.pdf) that I have found useful as the School budget is formatted a bit differently than the City's budget.  

The school budget is about as large as the city budget (both about $20M ), and therefore is presented separately. The school board (9 elected members; 3 from each ward) have developed the presented budget over the course of the year. 



# FY2027 Proposed Revenues
- Total Revenues: 19,325,338
    - Total State and Federal: $9,252,690
    - Total Property tax portion (District appropriation and Ed tax): $7,268,764
    - Total grants: $2,133,883
    - Food service: $670,000
- The school offsets some of its cost via state and federal aid and private grants
- State adequacy aid has dropped ~550k (~6%) from the previous year. This is due to a change in number of kids qualifying for aid in the district, along with changes to the total amount the state is willing to disburse.
- Last year the School district used fund balance (rainy day fund) to make balance their budget. 

----

While developing the school expenditures, the school board and asked the district administrators to prepare 3 budgets: 

- Option 1. A 'fix it' budget
    - This budget would stabilize the school and meet the needs of the community
    - This budget was more than $5M over the tax cap baseline budget. 

- Option 2. A recommended budget
    - This budget understands the realities of the tax cap and and seeks to retain student programs like sports, drama, as well as district wide positions. 
    - This budget was approximately $2M above the tax cap baseline

- Option 3. A tax cap budget
    - This budget sacrifices teachers and support staff to meet the tax cap. 
    - This budget was at the tax cap. 


At the School budget workshop on 6/8/26, the board presented the school board approved budget(option 2 above). After deliberating, the City council voted to direct them to present a tax capped budget. 

### How Sam Sees it: 
I think the city should be funding the recommended amount. The impacts of a tax capped budget are stark including: 

- Elimination of 19.75 filled positions (These jobs are currently filled)
    - Paul Smith Elementary
        - 1 Behavior support
        - 0.5 custodians at PSS
        - 1 Art teacher
        - 1 Classroom teacher 
        - 0.75 Reading specialist
    - Franklin Middle school
        - 1 Assistant principal
        - 0.25 reading specialist
        - 2 Classroom teachers
        - 1 Computer teacher
        - 1 Nurse
        - 0.5 Music teacher
        - 1 Social worker
        - 1 Special education case manager
    - Franklin High School
        - 1 Custodian
        - 1 Math teacher
        - 0.5 Music teacher
    - District Level
        - 1 Library/media specialist
        - 1 Accounts payable
        - 1 Maintenance person
        - 1 Tech integrator
        - 0.25 Superintendent staff
        - 1 Athletic director
- I'm not certain that a tax capped budget is legal, with the reduction of a school nurse, and special education case manager. This has been referred to the city attorney. 
- The tax capped budget effectively lays off 7 teachers (classroom, computer, art, music)
- The tax capped budget removes custodians and maintenance, potentially increasing replacement costs in the future. Repairing is almost always cheaper than replacing. 
- the tax capped budget removes the nurse from the middle school. 
The tax capped budget removes 30 open positions as well. Open positions are positions that the department (school, fire, police) recognizes that they need, but do not have someone in it yet. In other words, filled positions are like layoffs, while open positions are paper positions. 
- The city council should be looking for ways to avoid the tax capped budget
    - There are two sections of the tax cap that may be utilized to bring additional revenue to the school; one relies on replacing lost revenue from other sources (loss of state adequacy aid), while the other relies on the legal duty the city has to its students. 
